# Generated by Django 2.0.9 on 2018-12-18 08:44

import datetime
from django.db import migrations, models
import django_es_example.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 12, 18, 8, 44, 25, 301840), verbose_name='birthday'),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='More than 4 characters and lower case.', max_length=150, unique=True, validators=[django_es_example.users.models.CustomUsernameValidator()], verbose_name='username'),
        ),
    ]
