# Generated by Django 2.0.9 on 2018-12-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181218_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, help_text='Date type: YYYY-MM-DD', verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Required, less than 20 characters.', max_length=20, verbose_name='first name'),
        ),
    ]
